# Author's Notes: Only for evaluation.

# Property of Microsoft.
# Source: Swin-Transformer/configs/swin/swin_large_patch4_window12_384_22kto1k_finetune.yaml

DATA:
  IMG_SIZE: 384
MODEL:
  TYPE: swin
  NAME: swin_large_patch4_window12_384
  SWIN:
    EMBED_DIM: 192
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 6, 12, 24, 48 ]
    WINDOW_SIZE: 12
TEST:
  CROP: False