# Author's Notes: Only for evaluation.

# Property of Microsoft.
# Source: Modified version of configs/swin/swin_base_patch4_window12_384_22kto1k_finetune.yaml

DATA:
  IMG_SIZE: 384
MODEL:
  TYPE: swin
  NAME: swin_base_patch4_window12_384
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 12
TEST:
  CROP: False